Часть 5 Acceptance тестирование
DasRegal/qna pull request #3
Opened 2017-08-24 08:05 UTC by DasRegal

2017-08-24 13:31 UTC, vkurennov requested changes

2017-08-24 13:31 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +  def index
Все ответы на странице вопроса, поэтому экшн index не нужен

2017-08-24 13:31 UTC, vkurennov commented on app/controllers/answers_controller.rb
>    def new
Форма ответа должна быть на странице вопроса, поэтому экшн new не нужен

2017-08-24 13:31 UTC, vkurennov commented on app/controllers/answers_controller.rb
>        render :new
рендерить нужно ту страницу, на которой юзер заполнял форму, т.е. страницу вопроса

2017-08-24 13:31 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +  def is_author?(answer)
1. Вынеси этот метод в модель User, он нам еще не раз пригодится.
2. Не нужно возвращать true/false в явном виде, ведь просто сравнение `answer.user_id == current_user.id` уже вернет true/false, а последнее выражение в методе - это и есть возвращаемое им значение. Если метод состоит из одной строки, то он и вернет значение сравнения.

2017-08-24 13:31 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +    if @question.user == current_user
1. Проверяй по id
2. Используй метод `User#is_author?`

2017-08-24 13:31 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +  def is_author?(question)
1. Дублирование с методом в Answer, именно поэтому его и надо выносить
2. ты нигде не используешь этот метод в этом контроллере

2017-08-24 13:31 UTC, vkurennov commented on app/views/questions/new.html.slim
> += form_for @question do |f|
Нужен вывод ошибок валидации

2017-08-24 13:31 UTC, vkurennov commented on app/views/questions/show.html.slim
> +p =link_to 'Delete', question_path(@question), method: :delete
Зачем всем показывать ссылку на удаление? Показывай только автору. Здесь опять же пригодится метод `User#is_author?`

2017-08-24 13:31 UTC, vkurennov commented on app/views/questions/show.html.slim
> +  -if answer.body.present?
Лучше проверять на `answer.persisted?`

2017-08-24 13:31 UTC, vkurennov commented on app/views/questions/show.html.slim
> +  -if answer.user == current_user
Замени на `User#is_author?`

2017-08-24 13:31 UTC, vkurennov commented on app/views/questions/show.html.slim
> += form_for [@question, Answer.new] do |f|
Нужен вывод ошибок валидации

2017-08-24 13:31 UTC, vkurennov commented on spec/acceptance/answers/create_answer_spec.rb
> +    expect(page).to have_content 'Your answer successfully created.'
Нужно проверить наличие ответа на странице

2017-08-24 13:31 UTC, vkurennov commented on spec/acceptance/answers/create_answer_spec.rb
> +feature 'Create answer', %q{
Нужен тест на ошибки валидации - проверить, что система выводит их пользователю.

2017-08-24 13:31 UTC, vkurennov commented on spec/acceptance/answers/delete_answer_spec.rb
> +    expect(page).to have_content 'Your answer is deleted.'
Нужно проверить остутсвие ответа на странице после удаления

2017-08-24 13:31 UTC, vkurennov commented on spec/acceptance/answers/delete_answer_spec.rb
> +  scenario 'Any user can delete question' do
Почему can?  can not

2017-08-24 13:31 UTC, vkurennov commented on spec/acceptance/questions/create_question_spec.rb
> +feature 'Create question', %q{
Нужен тест на ошибки валидации - проверить, что система выводит их пользователю.

2017-08-24 13:31 UTC, vkurennov commented on spec/acceptance/questions/create_question_spec.rb
> +    expect(page).to have_content 'Your question successfully created.'
Нужно проверить заголовок и тело вопроса на странице

2017-08-24 13:31 UTC, vkurennov commented on spec/acceptance/questions/delete_question_spec.rb
> +    expect(page).to have_content 'Your question is deleted.'
Нужно проверить, что вопроса больше нет на странице

2017-08-24 13:31 UTC, vkurennov commented on spec/acceptance/questions/delete_question_spec.rb
> +    click_on 'Delete'
Зачем вообще показывать ссылку на удаление не-автору?

2017-08-24 13:31 UTC, vkurennov commented on spec/acceptance/questions/delete_question_spec.rb
> +  scenario 'Any user can delete question' do
Опять же can not

2017-08-24 13:31 UTC, vkurennov commented on spec/acceptance/questions/watch_questions_spec.rb
> +    expect(page).to have_content 'Ask question'
Это не доказывать наличие списка вопросов на странице, только наличие ссылки.

2017-08-24 13:31 UTC, vkurennov commented on spec/acceptance/questions/watch_questions_spec.rb
> +    expect(page).to have_content 'Answers to question'
Тут нужно проверять не только ответ, но и сам вопрос. А ответы надо проверять списком, т.е. их должно быть несколько и они должны быть разными

2017-08-24 13:31 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
где тесты на destroy?

2017-08-24 13:31 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
>      context 'with valid attributes' do
Тут нужно проверить связь с залогиненным юзером

2017-08-24 13:31 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
>      context 'with valid attributes' do
Тут нужно проверить связь с залогиненным юзером

2017-08-24 13:31 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
> +      @user = create(:user, :with_questions)
Мы выносили это в хелпер, чтобы не дублировать каждый раз

2017-08-24 13:31 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
> +  describe 'DELETE #destroy' do
У тебя же при удалении условие, нужно проверять оба варианта: для автора и для не-автора, лучше всего в разных контекстах

2017-08-24 13:31 UTC, vkurennov commented on spec/models/user_spec.rb
> +RSpec.describe User do
А тесты на новые ассоциации?

2017-08-25 03:50 UTC, DasRegal commented on app/controllers/answers_controller.rb
>        render :new
Тогда GET #new вообще не нужен в тесте контроллера Answers. Верно?

2017-08-25 09:46 UTC, DasRegal commented on spec/controllers/answers_controller_spec.rb
>      context 'with valid attributes' do
Не понял, что требуется.

2017-08-25 10:38 UTC, vkurennov requested changes

2017-08-25 10:38 UTC, vkurennov commented on spec/acceptance/answers/create_answer_spec.rb
> +    fill_in 'Title', with: 'Text answer'
зачем ответу заголовок? Ну и если уж он есть, то стои и его проверить на странцие. А если ты его не выводишь, то зачем его вводить?

2017-08-25 10:38 UTC, vkurennov commented on spec/acceptance/questions/watch_questions_spec.rb
> +
Тут нет проверки на список вопросов.

2017-08-25 10:38 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
>      context 'with valid attributes' do
Нужен тест на связь созданного овтета с залогиненным юзером.

2017-08-25 10:38 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +      before { question_with_answers.answers.first.update(user_id: @user.id) }
Лучше вынести в `let` вызов `question_with_answers.answers.first`, чтобы не писать везде такие длинные конструкции:

`let(:answer) { question_with_answers.answers.first }`

2017-08-25 10:38 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
>      context 'with valid attributes' do
Не исправлено

2017-08-25 10:38 UTC, vkurennov commented on spec/models/user_spec.rb
> +RSpec.describe User do
И где тест на метод `author_of?` Прежде чем писать какой-либо код, проверь, есть ли тесты, если нет, начни с них.

2017-08-25 10:42 UTC, DasRegal commented on spec/controllers/questions_controller_spec.rb
>      context 'with valid attributes' do
Не понимаю, что требуется.

2017-08-25 11:00 UTC, DasRegal commented on spec/acceptance/questions/watch_questions_spec.rb
> +
И не должно быть. Это просмотр одного вопроса.

2017-08-25 11:12 UTC, DasRegal commented on spec/controllers/questions_controller_spec.rb
>      context 'with valid attributes' do
Разобрался

2017-08-25 12:56 UTC, vkurennov approved these changes

2017-08-25 12:56 UTC, vkurennov commented on spec/acceptance/questions/watch_questions_spec.rb
> +
Тогда как этот тест доказывает, что пользователь видит один вопрос? Он видит ссылку, но не вопрос.

2017-08-25 13:17 UTC, merged