Часть 6 Ajax ч1
DasRegal/qna pull request #4
Opened 2017-08-26 15:52 UTC by DasRegal

2017-08-26 20:29 UTC, darialapina requested changes

2017-08-26 20:29 UTC, darialapina commented on app/views/answers/create.js.erb
> +$('.answers').append('<%= j render @answer %>');
Нужно ошибки валидаций выводить. Именно валидаций, а не noticeиз контроллера. Одно другое не отменяет.

2017-08-26 20:29 UTC, darialapina commented on app/views/questions/show.html.slim
>  -if @answer&.errors
Так как при добавлении ответа через ajax страница не будет обновляться, то здесь ошибки не выведутся.

2017-08-26 20:29 UTC, darialapina commented on spec/acceptance/answers/create_answer_spec.rb
> -    expect(page).to have_content 'Body can\'t be blank'
Если добавишь вывод ошибок валидации, то и это ожидание будет выполняться.

2017-08-27 09:24 UTC, vkurennov approved these changes

2017-08-27 12:32 UTC, merged