Часть 7 Ajax ч2
DasRegal/qna pull request #5
Opened 2017-08-31 11:14 UTC by DasRegal

2017-08-31 11:59 UTC, vkurennov requested changes

2017-08-31 11:59 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +      @question.answers.update_all(is_favorite: false)
Это бизнес-логика, ей не место в контроллере, ее надо вынести в модель, а здесь просто вызывать метод. И т.к. тут несколько обновлений, нужно применить [транзакцию](http://api.rubyonrails.org/classes/ActiveRecord/Transactions/ClassMethods.html).

2017-08-31 11:59 UTC, vkurennov commented on app/views/answers/_answer.html.slim
> +      -if !answer.is_favorite
Используй unless

2017-08-31 11:59 UTC, vkurennov commented on app/views/answers/favorite.js.erb
> +$('.answers').html('<%= j render @question.answers.order(is_favorite: :desc) %>')
сделай именованый скоуп для этого

2017-08-31 11:59 UTC, vkurennov commented on app/views/answers/update.js.erb
> +  $('.answers').html('<%= j render @answer %>');
Нужно обновлять только измененный ответ, а не весь список

2017-08-31 11:59 UTC, vkurennov commented on app/views/questions/show.html.slim
> +  = render @question.answers.order(is_favorite: :desc)
Используй скоуп, иначе получается дублирование

2017-08-31 11:59 UTC, vkurennov commented on config/routes.rb
> +      patch 'favorite', on: :member
Названия кастомных экшенов лучше тоже задавать символом, они и нужны, чтобы такие вот строки-идентификаторы задавать

2017-08-31 12:19 UTC, DasRegal commented on app/views/answers/favorite.js.erb
> +$('.answers').html('<%= j render @question.answers.order(is_favorite: :desc) %>')
Это как? Не понимаю

2017-08-31 13:01 UTC, darialapina commented on app/views/answers/favorite.js.erb
> +$('.answers').html('<%= j render @question.answers.order(is_favorite: :desc) %>')
[http://api.rubyonrails.org/classes/ActiveRecord/Scoping/Named/ClassMethods.html#method-i-scope](http://api.rubyonrails.org/classes/ActiveRecord/Scoping/Named/ClassMethods.html#method-i-scope)

2017-09-01 08:33 UTC, vkurennov requested changes

2017-09-01 08:33 UTC, vkurennov commented on app/models/answer.rb
> +      self.update(is_favorite: true)
транзакция откатывается только в случе исключения, поэтому нужно здесь использовать `update!`

2017-09-01 08:33 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
>  RSpec.describe AnswersController, type: :controller do
Где тесты на экшн favorite?

2017-09-01 08:33 UTC, vkurennov commented on app/models/answer.rb
> +  def set_favorite
Где тесты модели на этот метод? **Люой код**, написанный тобой, должен быть покрыт тестами

2017-09-06 09:29 UTC, vkurennov requested changes

2017-09-06 09:29 UTC, vkurennov commented on spec/models/answer_spec.rb
> +    it 'check funtion' do
Что за check function? Описывай, что делает метод, например "sets favorite flag to true"

2017-09-06 09:29 UTC, vkurennov commented on spec/models/answer_spec.rb
> +  context 'Mark answer to favorite' do
При тестировании методов в моделях, для каждого метода создается отдельный describe в названии которого указывается имя метода, например:

`describe "#set_favorite"`

2017-09-06 09:29 UTC, vkurennov commented on spec/models/answer_spec.rb
> +    it 'check funtion' do
И нужен еще один тест, проверяющий, что с уже существующего лучшего ответа флаг снимается

2017-09-06 11:32 UTC, vkurennov approved these changes

2017-09-17 06:21 UTC, merged