Часть 8 Nested forms
DasRegal/qna pull request #6
Opened 2017-09-20 17:23 UTC by DasRegal

2017-09-20 19:54 UTC, darialapina requested changes

2017-09-20 19:54 UTC, darialapina commented on app/controllers/attachments_controller.rb
> +
Аутентификация?

2017-09-20 19:54 UTC, darialapina commented on app/models/answer.rb
> +  has_many :attachments, as: :attachable
При удалении ответа, нужно чтобы файлы тоже удалялись.

2017-09-20 19:54 UTC, darialapina commented on app/models/question.rb
> +  has_many :attachments, as: :attachable
Аналогично, файлы удаляем при удалении вопроса

2017-09-20 19:54 UTC, darialapina commented on app/views/answers/_answer.html.slim
> +      = render 'share/attachments', obj: answer
Отступ

2017-09-20 19:54 UTC, darialapina commented on spec/acceptance/answers/delete_file_from_answer.rb
> +    sign_in(@user)
Нужен сценарий с неаутентифицированным пользователем.
Это решило бы проблему с косяком во представлении для рендеринга файла к ответу (или вопросу, зависит от obj).

2017-09-20 19:54 UTC, darialapina commented on spec/acceptance/questions/delete_file_from_question_spec.rb
> +    sign_in(@user)
В этой спеке сценарий с гостем с одной стороны нужен, с другой - можно пропустить)
Корректность скрытия от гостя ссылки на удаления будет проверяться в спеке удаления файла для ответа, так как используется один partial при рендеринге.

2017-09-20 19:54 UTC, darialapina commented on spec/controllers/attachments_controller_spec.rb
> +    end
Нужна проверка на случай злоумышленника неаутентифицированного.
Сейчас бы у тебя тест на такой случай упал, так как нет проверки в контроллере.

2017-09-20 19:54 UTC, darialapina commented on spec/models/answer_spec.rb
> +  it { should accept_nested_attributes_for :attachments }
не все опции протестированы
`.allow_destroy(true)`

2017-09-20 19:54 UTC, darialapina commented on spec/models/question_spec.rb
> +  it { should accept_nested_attributes_for :attachments }
и тут тоже

2017-09-20 19:54 UTC, darialapina commented on app/views/share/_attachments.html.slim
> +      -if current_user.author_of?(obj)
Не хватает тестов. Вот тут всё упадёт для гостя.

2017-09-20 19:54 UTC, darialapina commented on spec/acceptance/answers/add_files_to_answer.rb
> +  scenario 'User can add multiply files when answering', js: true do
Достаточно только этого сценария, где несколько файлов добавляется, т.к. добавление 1-го файла - это частный случай.

2017-09-20 19:54 UTC, darialapina commented on spec/acceptance/questions/add_files_to_question_spec.rb
> +  scenario 'User can add multiply files when asks question', js: true do
Достаточно только этого сценария, где несколько файлов добавляется, т.к. добавление 1-го файла - это частный случай.

2017-09-21 04:14 UTC, DasRegal commented on spec/acceptance/answers/delete_file_from_answer.rb
> +    sign_in(@user)
Есть же такой сценарий:
```
scenario 'any user can not delete'
@answer.update(user: user2)
```

2017-09-21 13:53 UTC, vkurennov approved these changes

2017-09-21 14:31 UTC, merged

2017-09-21 14:37 UTC, darialapina commented on spec/acceptance/answers/delete_file_from_answer.rb
> +    sign_in(@user)
Я имела ввиду, когда пользователь совсем не залогинен.
У тебя во паршале для  файла не было проверки, что current_user есть.
А из-за блока background получалось, что сценарий
scenario 'any user can not delete'
проверял для не автора, соответственно, current_user был и тест проходил.